---
default_stages: [commit]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # We re-set the `stages` setting because pre-commit-hooks over-rides it
      # otherwise.
      # See https://github.com/pre-commit/pre-commit-hooks/issues/515
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [commit]

      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
